name: Build and Create PR

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated PR from ${{ github.ref_name }}
          title: '[Automated] PR from ${{ github.ref_name }}'
          body: |
            This is an automated pull request created from branch ${{ github.ref_name }}.
            
            Changes included in this PR:
            ${{ github.event.head_commit.message }}
          base: master
          branch: automated-pr/${{ github.ref_name }}
          delete-branch: true