name: Build and Create PR

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Check for changes against master
        run: |
          git fetch origin master:master
          COUNT=$(git rev-list --right-only --count master...HEAD)
          if [ $COUNT -eq 0 ]; then
            echo "No changes to create a PR. Branch is not ahead of master."
            exit 1
          else
            echo "Found $COUNT commits ahead of master. Proceeding with PR creation."
          fi

      - name: Force push branch for PR
        run: |
          git checkout -b automated-pr/${{ github.ref_name }}
          git push origin automated-pr/${{ github.ref_name }} --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated PR from ${{ github.ref_name }}
          title: '[Automated] PR from ${{ github.ref_name }}'
          body: |
            This is an automated pull request created from branch ${{ github.ref_name }}.
            
            Changes included in this PR:
            ${{ github.event.head_commit.message }}
          base: master
          branch: automated-pr/${{ github.ref_name }}
          delete-branch: true