name: Create PR on push

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Check for changes against master
        id: check-changes
        run: |
          git fetch origin master:master
          COUNT=$(git rev-list --right-only --count master...HEAD)
          if [ $COUNT -eq 0 ]; then
            echo "No changes to create a PR. Branch is not ahead of master."
            echo "create_pr=false" >> $GITHUB_OUTPUT
          else
            echo "Found $COUNT commits ahead of master. Proceeding with PR creation."
            echo "create_pr=true" >> $GITHUB_OUTPUT
          fi

      - name: Check if PR already exists
        id: check-pr
        if: steps.check-changes.outputs.create_pr == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh pr list -H ${{ github.ref_name }} -B master --state open --json number --jq '.[] | .number' | grep -q .; then
            echo "pr_exists=true" >> $GITHUB_OUTPUT
          else
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-pr.outputs.pr_exists == 'false' && steps.check-changes.outputs.create_pr == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -B master -H ${{ github.ref_name }} \
            --title "[Automated] PR from ${{ github.ref_name }}" \
            --body "This is an automated pull request created from branch ${{ github.ref_name }}.\n\nChanges included: ${{ github.event.head_commit.message }}"